export const API = {
  UNAUTHORIZE: 'UNAUTHORIZE',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  ERROR: 'ERROR',
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  EDITED: 'EDITED',
  DELETED: 'DELETED'
}

export const EVENT = {
  UNAUTHORIZED: 'EVENT_UNAUTHORIZED'
}

export const USER_STATUS = {
  ACTIVE: 'Active',
  PENDING: 'Pending',
  BANNED: 'Banned',
  BLOCK: 'Block'
}

export const BILLING_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  REJECTED: 'REJECTED'
}

export const MENU_CATEGORY_STATUS = {
  ACTIVE: 'ACTIVE',
  DELETED: 'DELETED'
}

export const DEFAULT_STATUS = {
  ACTIVE: 'ACTIVE',
  DELETED: 'DELETED'
}

export const FOOD_ITEM_STATUS = {
  ACTIVE: 'ACTIVE',
  DELETED: 'DELETED'
}

export const ORDER_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  IN_PROGRESS: 'IN_PROGRESS',
  READY: 'READY',
  DUE: 'DUE',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED'
}

export const ORDER_TABLE_STATUS = {
  VACANT: 'VACANT',
  ON_GOING: 'ON_GOING'
}

export const RESERVATION_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  CANCELED: 'CANCELED',
  FINISH: 'FINISH'
}
